// <auto-generated />
namespace VOS_Dist_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class categoryFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201611290129065_categoryFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
