// <auto-generated />
namespace VOS_Dist_Site.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnalyticsFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnalyticsFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201611251746534_AnalyticsFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
